### ISSUE TITLE
Ad on Heise.de from double-click

### ISSUE THREAD

**Issue by domhardt** [fboes/fritzbox-blacklist#5]
Hello,

I'am using your filter list and  doubleclick should be filtered. But there is an ad on Heise.de with a doubleclick-link:
http://pubads.g.doubleclick.net/gampad/clk?id=41555030&iu=/6514/www.heise.de/clicktracking/usAd

![bildschirmfoto 2016-05-21 um 23 35 49](https://cloud.githubusercontent.com/assets/1955290/15450957/3808bc76-1fad-11e6-8839-5dc39df1b734.png)

Suggestions?

**Comment by fboes** [comment]
Awesome find. Maybe the blocking mechanism is confused if there are to many dots stacked in the subdomain-part?

Could you please try one of the following entries to your Fritz Box' black list each at a time and note when the ad is removed:

1. doubleclick.net
2. g.doubleclick.net
3. pubads.g.doubleclick.net

Another idea: Maybe this an HTTPS ad. These cannot be filtered by the Fritz Box.

**Comment by fboes** [comment]
I just had a different idea: Maybe the image you are seeing is not being served from doubleclick.net; the Fritz Box does only block resources being loaded from blacklisted domains. It does not block links in HTML source code. If you'd click on this link, the Fritz Box should stop you from following that link.

**Comment by fboes** [comment]
No further information given, possibly solved by comment from 24 Oct 2016
