### ISSUE TITLE
Netflix geblockt

### ISSUE THREAD

**Issue by Auke** [fboes/fritzbox-blacklist#6]
Hi,

da conduit.com (u. a. 198.49.162.233) denselben Adressblock wie die Videoserver von Netflix (u. a. 198.38.117.134, 198.38.117.140, 198.38.117.152) benutzt, funktioniert Netflix nicht mehr, wenn conduit.com auf der Blacklist steht. Zumindest die Wii-U-App lädt Filme dann ewig und zeigt bei 100% einen Fehler an. Die Fritzbox scheint den gesamten Adressblock (198.36.47.0-198.51.11.255) zu blocken.

Ich empfehle die Verschiebung von fritzbox-blacklist.txt nach fritzbox-blacklist-extra.txt ;-)

Grüße, Auke

**Comment by fboes** [comment]
Can you see the blocked request in Fritz Box' system log? They should show up there.

Otherwise: Are there reproducible results with Netflix not running as long as the filter is in effect, and Netflix running when the filter is not in effect?

If the Fritz Box block IP blocks, this would be a rather serious error, because this may as well block tons of other sites as well.

**Comment by Auke** [comment]
> Can you see the blocked request in Fritz Box' system log? They should show up there.

Yes. They (198.38.117.134, 198.38.117.140, 198.38.117.152) show up in the log.

> Otherwise: Are there reproducible results with Netflix not running as long as the filter is in effect, and Netflix running when the filter is not in effect?

Yes. Netflix does work, if I put the Wii U in a a profile, on which the blacklist does not apply.

**Comment by fboes** [comment]
Um, interessant. Taucht den diese Blockade im Ereignis-Protokoll der
Fritz-Box auf? Das sollten wir auf jeden Fall testen, denn das würde ja
bedeuten, dass ganz andere Dienste und Seiten davon betroffen sein können.

**Comment by fboes** [comment]
Thx for reporting that. I have that listed unter [Know issues](https://github.com/fboes/fritzbox-blacklist#know-issues).
